 import { createRouter, createWebHistory } from 'vue-router';                                                                                                                                                          
  import CountryList from '../views/CountryList.vue';                                                                                                                                                                   
                                                                                                                                                                                                                        
const routes = [                                                                                                                                                                                                      
      {                                                                                                                                                                                                                 
          path: '/countries',                                                                                                                                                                                           
          component: CountryList                                                                                                                                                                                        
      }                                                                                                                                                                                                                 
]                                                                                                                                                                                                                     
                                                                                                                                                                                                                        
const router = createRouter({                                                                                                                                                                                         
      history: createWebHistory(),                                                                                                                                                                                      
      routes,                                                                                                                                                                                                           
  })                                                                                                                                                                                                                    
                                                                                                                                                                                                                        
export default router                               
