import random

from django.core.management.base import BaseCommand
from faker import Faker

fake = Faker()

CARRIERS = ["FedEx", "DHL", "UPS", "SpeedyShip"]
STATUSES = ["In Transit", "Delivered", "Out for Delivery", "Pending Pickup", "Delayed"]


class Command(BaseCommand):
    help = "Generate fake shipping tracking data and write it to shipping/mock_data.py"

    def add_arguments(self, parser):
        parser.add_argument("--count", type=int, default=1000)

    def handle(self, *args, **options):
        count = options["count"]
        records = {}
        for _ in range(count):
            tracking_number = f"TRACK{fake.unique.random_number(digits=6, fix_len=True)}"
            records[tracking_number] = {
                "carrier": random.choice(CARRIERS),
                "status": random.choice(STATUSES),
                "estimated_delivery": fake.date_between(start_date="today", end_date="+14d").isoformat(),
            }

        with open("shipping/mock_data.py", "w") as f:
            f.write("# Generated by seed_shipping_mock_data - do not edit by hand\n")
            f.write("# Simulates external carrier data - no local model, nothing persisted to the DB\n\n")
            f.write("MOCK_CARRIER_DATA = {\n")
            for tracking_number, record in records.items():
                f.write(f"    {tracking_number!r}: {record!r},\n")
            f.write("}\n")

        self.stdout.write(self.style.SUCCESS(f"Generated {count} mock shipping records in shipping/mock_data.py"))
