# Generated by Django 6.1.1 on 2026-09-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='local_code',
            new_name='continent',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='local_vat',
            new_name='vat_rate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='local_address',
        ),
    ]
