# Generated by Django 6.1.1 on 2026-09-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['purchase_date', 'id']},
        ),
    ]
