# Generated by Django 6.1.1 on 2026-09-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', 'id']},
        ),
    ]
