# Generated by Django 6.1.1 on 2026-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='continent',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='title',
        ),
        migrations.AddField(
            model_name='purchase',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
