"""
Real countries with an accurate continent and a realistic VAT/sales-tax
rate, used to seed the Country reference table (one row per country,
not one per purchase). See AGENTS.md.

Each entry: (name, country_code, continent, vat_rate)
"""

COUNTRIES = [
    # Europe (44)
    ("Albania", "AL", "Europe", 19.00), ("Andorra", "AD", "Europe", 4.50),
    ("Austria", "AT", "Europe", 20.00), ("Belarus", "BY", "Europe", 20.00),
    ("Belgium", "BE", "Europe", 21.00), ("Bosnia and Herzegovina", "BA", "Europe", 17.00),
    ("Bulgaria", "BG", "Europe", 20.00), ("Croatia", "HR", "Europe", 25.00),
    ("Cyprus", "CY", "Europe", 19.00), ("Czech Republic", "CZ", "Europe", 21.00),
    ("Denmark", "DK", "Europe", 25.00), ("Estonia", "EE", "Europe", 20.00),
    ("Finland", "FI", "Europe", 24.00), ("France", "FR", "Europe", 20.00),
    ("Germany", "DE", "Europe", 19.00), ("Greece", "GR", "Europe", 24.00),
    ("Hungary", "HU", "Europe", 27.00), ("Iceland", "IS", "Europe", 24.00),
    ("Ireland", "IE", "Europe", 23.00), ("Italy", "IT", "Europe", 22.00),
    ("Kosovo", "XK", "Europe", 18.00), ("Latvia", "LV", "Europe", 21.00),
    ("Liechtenstein", "LI", "Europe", 7.70), ("Lithuania", "LT", "Europe", 21.00),
    ("Luxembourg", "LU", "Europe", 17.00), ("Malta", "MT", "Europe", 18.00),
    ("Moldova", "MD", "Europe", 20.00), ("Monaco", "MC", "Europe", 20.00),
    ("Montenegro", "ME", "Europe", 21.00), ("Netherlands", "NL", "Europe", 21.00),
    ("North Macedonia", "MK", "Europe", 18.00), ("Norway", "NO", "Europe", 25.00),
    ("Poland", "PL", "Europe", 23.00), ("Portugal", "PT", "Europe", 23.00),
    ("Romania", "RO", "Europe", 19.00), ("San Marino", "SM", "Europe", 17.00),
    ("Serbia", "RS", "Europe", 20.00), ("Slovakia", "SK", "Europe", 20.00),
    ("Slovenia", "SI", "Europe", 22.00), ("Spain", "ES", "Europe", 21.00),
    ("Sweden", "SE", "Europe", 25.00), ("Switzerland", "CH", "Europe", 8.10),
    ("Ukraine", "UA", "Europe", 20.00), ("United Kingdom", "GB", "Europe", 20.00),

    # Asia (48)
    ("Afghanistan", "AF", "Asia", 10.00), ("Armenia", "AM", "Asia", 20.00),
    ("Azerbaijan", "AZ", "Asia", 18.00), ("Bahrain", "BH", "Asia", 10.00),
    ("Bangladesh", "BD", "Asia", 15.00), ("Bhutan", "BT", "Asia", 7.00),
    ("Brunei", "BN", "Asia", 0.00), ("Cambodia", "KH", "Asia", 10.00),
    ("China", "CN", "Asia", 13.00), ("Georgia", "GE", "Asia", 18.00),
    ("India", "IN", "Asia", 18.00), ("Indonesia", "ID", "Asia", 11.00),
    ("Iran", "IR", "Asia", 9.00), ("Iraq", "IQ", "Asia", 15.00),
    ("Israel", "IL", "Asia", 17.00), ("Japan", "JP", "Asia", 10.00),
    ("Jordan", "JO", "Asia", 16.00), ("Kazakhstan", "KZ", "Asia", 12.00),
    ("Kuwait", "KW", "Asia", 0.00), ("Kyrgyzstan", "KG", "Asia", 12.00),
    ("Laos", "LA", "Asia", 10.00), ("Lebanon", "LB", "Asia", 11.00),
    ("Malaysia", "MY", "Asia", 10.00), ("Maldives", "MV", "Asia", 8.00),
    ("Mongolia", "MN", "Asia", 10.00), ("Myanmar", "MM", "Asia", 5.00),
    ("Nepal", "NP", "Asia", 13.00), ("North Korea", "KP", "Asia", 0.00),
    ("Oman", "OM", "Asia", 5.00), ("Pakistan", "PK", "Asia", 17.00),
    ("Palestine", "PS", "Asia", 16.00), ("Philippines", "PH", "Asia", 12.00),
    ("Qatar", "QA", "Asia", 0.00), ("Saudi Arabia", "SA", "Asia", 15.00),
    ("Singapore", "SG", "Asia", 9.00), ("South Korea", "KR", "Asia", 10.00),
    ("Sri Lanka", "LK", "Asia", 18.00), ("Syria", "SY", "Asia", 10.00),
    ("Taiwan", "TW", "Asia", 5.00), ("Tajikistan", "TJ", "Asia", 15.00),
    ("Thailand", "TH", "Asia", 7.00), ("Timor-Leste", "TL", "Asia", 2.50),
    ("Turkey", "TR", "Asia", 20.00), ("Turkmenistan", "TM", "Asia", 15.00),
    ("United Arab Emirates", "AE", "Asia", 5.00), ("Uzbekistan", "UZ", "Asia", 12.00),
    ("Vietnam", "VN", "Asia", 10.00), ("Yemen", "YE", "Asia", 5.00),

    # Africa (51)
    ("Algeria", "DZ", "Africa", 19.00), ("Angola", "AO", "Africa", 14.00),
    ("Benin", "BJ", "Africa", 18.00), ("Botswana", "BW", "Africa", 14.00),
    ("Burkina Faso", "BF", "Africa", 18.00), ("Burundi", "BI", "Africa", 18.00),
    ("Cabo Verde", "CV", "Africa", 15.00), ("Cameroon", "CM", "Africa", 19.25),
    ("Central African Republic", "CF", "Africa", 19.00), ("Chad", "TD", "Africa", 18.00),
    ("Comoros", "KM", "Africa", 10.00), ("Congo (Republic)", "CG", "Africa", 18.00),
    ("DR Congo", "CD", "Africa", 16.00), ("Djibouti", "DJ", "Africa", 10.00),
    ("Egypt", "EG", "Africa", 14.00), ("Equatorial Guinea", "GQ", "Africa", 15.00),
    ("Eritrea", "ER", "Africa", 5.00), ("Eswatini", "SZ", "Africa", 15.00),
    ("Ethiopia", "ET", "Africa", 15.00), ("Gabon", "GA", "Africa", 18.00),
    ("Gambia", "GM", "Africa", 15.00), ("Ghana", "GH", "Africa", 15.00),
    ("Guinea", "GN", "Africa", 18.00), ("Guinea-Bissau", "GW", "Africa", 15.00),
    ("Ivory Coast", "CI", "Africa", 18.00), ("Kenya", "KE", "Africa", 16.00),
    ("Lesotho", "LS", "Africa", 15.00), ("Liberia", "LR", "Africa", 10.00),
    ("Libya", "LY", "Africa", 0.00), ("Madagascar", "MG", "Africa", 20.00),
    ("Malawi", "MW", "Africa", 16.50), ("Mali", "ML", "Africa", 18.00),
    ("Mauritania", "MR", "Africa", 16.00), ("Mauritius", "MU", "Africa", 15.00),
    ("Morocco", "MA", "Africa", 20.00), ("Mozambique", "MZ", "Africa", 16.00),
    ("Namibia", "NA", "Africa", 15.00), ("Niger", "NE", "Africa", 19.00),
    ("Nigeria", "NG", "Africa", 7.50), ("Rwanda", "RW", "Africa", 18.00),
    ("Senegal", "SN", "Africa", 18.00), ("Sierra Leone", "SL", "Africa", 15.00),
    ("Somalia", "SO", "Africa", 10.00), ("South Africa", "ZA", "Africa", 15.00),
    ("South Sudan", "SS", "Africa", 18.00), ("Sudan", "SD", "Africa", 17.00),
    ("Tanzania", "TZ", "Africa", 18.00), ("Togo", "TG", "Africa", 18.00),
    ("Tunisia", "TN", "Africa", 19.00), ("Uganda", "UG", "Africa", 18.00),
    ("Zambia", "ZM", "Africa", 16.00), ("Zimbabwe", "ZW", "Africa", 14.50),

    # North America (23, incl. Central America and the Caribbean)
    ("Antigua and Barbuda", "AG", "North America", 15.00),
    ("Bahamas", "BS", "North America", 10.00), ("Barbados", "BB", "North America", 17.50),
    ("Belize", "BZ", "North America", 12.50), ("Canada", "CA", "North America", 5.00),
    ("Costa Rica", "CR", "North America", 13.00), ("Cuba", "CU", "North America", 0.00),
    ("Dominica", "DM", "North America", 15.00), ("Dominican Republic", "DO", "North America", 18.00),
    ("El Salvador", "SV", "North America", 13.00), ("Grenada", "GD", "North America", 15.00),
    ("Guatemala", "GT", "North America", 12.00), ("Haiti", "HT", "North America", 10.00),
    ("Honduras", "HN", "North America", 15.00), ("Jamaica", "JM", "North America", 15.00),
    ("Mexico", "MX", "North America", 16.00), ("Nicaragua", "NI", "North America", 15.00),
    ("Panama", "PA", "North America", 7.00), ("Saint Kitts and Nevis", "KN", "North America", 17.00),
    ("Saint Lucia", "LC", "North America", 12.50),
    ("Saint Vincent and the Grenadines", "VC", "North America", 16.00),
    ("Trinidad and Tobago", "TT", "North America", 12.50),
    ("United States", "US", "North America", 0.00),

    # South America (12)
    ("Argentina", "AR", "South America", 21.00), ("Bolivia", "BO", "South America", 13.00),
    ("Brazil", "BR", "South America", 17.00), ("Chile", "CL", "South America", 19.00),
    ("Colombia", "CO", "South America", 19.00), ("Ecuador", "EC", "South America", 12.00),
    ("Guyana", "GY", "South America", 14.00), ("Paraguay", "PY", "South America", 10.00),
    ("Peru", "PE", "South America", 18.00), ("Suriname", "SR", "South America", 10.00),
    ("Uruguay", "UY", "South America", 22.00), ("Venezuela", "VE", "South America", 16.00),

    # Oceania (14)
    ("Australia", "AU", "Oceania", 10.00), ("Fiji", "FJ", "Oceania", 9.00),
    ("Kiribati", "KI", "Oceania", 0.00), ("Marshall Islands", "MH", "Oceania", 0.00),
    ("Micronesia", "FM", "Oceania", 0.00), ("Nauru", "NR", "Oceania", 0.00),
    ("New Zealand", "NZ", "Oceania", 15.00), ("Palau", "PW", "Oceania", 0.00),
    ("Papua New Guinea", "PG", "Oceania", 10.00), ("Samoa", "WS", "Oceania", 15.00),
    ("Solomon Islands", "SB", "Oceania", 10.00), ("Tonga", "TO", "Oceania", 15.00),
    ("Tuvalu", "TV", "Oceania", 0.00), ("Vanuatu", "VU", "Oceania", 15.00),
]
